export const SET_BALLOONS = 'SET_BALLOONS'
export const SET_BALLOONS_SUCCESS = 'SET_BALLOONS_SUCCESS'
export const SET_BALLOONS_FAIL = 'SET_BALLOONS_FAIL'

export const SET_BALLOONS_MORE = 'SET_BALLOONS_MORE'
export const SET_BALLOONS_MORE_SUCCESS = 'SET_BALLOONS_MORE_SUCCESS'
export const SET_BALLOONS_MORE_FAIL = 'SET_BALLOONS_MORE_FAIL'


export const REQUEST_BALLOONS_LIST = 'REQUEST_BALLOONS_LIST'
export const REQUEST_BALLOONS_LIST_RECEIVED = 'REQUEST_BALLOONS_LIST_RECEIVED'
export const REQUEST_BALLOONS_LIST_FAILED = 'REQUEST_BALLOONS_LIST_FAILED'
