export const URI = 'http://localhost:6543/2016'
export const AUTH_TOKEN_TYPE = 'Baerer'
export const AUTH_TOKEN = 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0NjQzMDExNDQsImdyb3VwIjoiand0Iiwic3ViIjoic2hlbGRvbkBkYXJrYml0cy5uZXQifQ.AvklRVFp-aZ4D9RfzgP9eJyyWrm_pwSvdVyzNpH20f-Q7QMFXX3tZUOVg3Nde2iRrEWee03yqNuENrlhCLxcGA'