export const SET_BALLOONS = 'SET_BALLOONS'
export const SET_BALLOONS_SUCCESS = 'SET_BALLOONS_SUCCESS'
export const SET_BALLOONS_FAIL = 'SET_BALLOONS_FAIL'
export const SET_CURRENT_BALLOON = 'SET_CURRENT_BALLOON'