export const SET_BALLOONS = 'SET_BALLOONS'
export const SET_BALLOONS_SUCCESS = 'SET_BALLOONS_SUCCESS'
export const SET_BALLOONS_FAIL = 'SET_BALLOONS_FAIL'

export const SET_BALLOONS_MORE = 'SET_BALLOONS_MORE'
export const SET_BALLOONS_MORE_SUCCESS = 'SET_BALLOONS_MORE_SUCCESS'
export const SET_BALLOONS_MORE_FAIL = 'SET_BALLOONS_MORE_FAIL'

export const SET_BALLOON = 'SET_BALLOON'
export const SET_BALLOON_SUCCESS = 'SET_BALLOON_SUCCESS'
export const SET_BALLOON_FAIL = 'SET_BALLOON_FAIL'
