export const SET_BALLOON = 'SET_BALLOON'
export const SET_BALLOON_SUCCESS = 'SET_BALLOON_SUCCESS'
export const SET_BALLOON_FAIL = 'SET_BALLOON_FAIL'

export const REQUEST_BALLOON_DETAIL = 'REQUEST_BALLOON_DETAIL'
export const REQUEST_BALLOONS_DETAIL_RECEIVED = 'REQUEST_BALLOONS_DETAIL_RECEIVED'
